let documents=[],lastQuestion='',lastSources=[],config=null;
$('#answer').innerHTML=empty('先从一个问题开始','无需API Key，也能检索并阅读原文。');$('#sources').innerHTML=empty('每条结论，都应该有出处','检索到的文档片段会显示在这里。');
function documentRows(items){return items.length?items.map(d=>`<div class="document-item" data-id="${d.id}"><span class="document-icon">▤</span><div class="document-info"><strong>${esc(d.name)}</strong><span class="small muted">${d.chunks} 个片段 · ${(d.characters/1000).toFixed(1)} 千字 · ${esc(d.kind)}</span></div><button class="btn secondary view-document" data-id="${d.id}">原文</button><button class="btn secondary delete-document" data-id="${d.id}">删除</button></div>`).join(''):empty('给知识库添一份资料','导入自己的笔记、手册或文本型PDF。');}
async function refresh(){documents=await api('/documents');$('#doc-count').textContent=documents.length;$('#chunk-count').textContent=documents.reduce((n,d)=>n+d.chunks,0)+' 个证据片段';$('#recent-docs').innerHTML=documentRows(documents.slice(0,5));$('#all-docs').innerHTML=documentRows(documents);$$('.view-document').forEach(b=>b.onclick=guard(async()=>{const doc=documents.find(d=>d.id===b.dataset.id);const chunks=await api('/documents/'+doc.id+'/chunks');$('#document-title').textContent=doc.name;$('#document-content').innerHTML=chunks.map(c=>`<article><span class="badge">第 ${c.page} 页 · 片段 ${c.idx+1}</span><pre>${esc(c.text)}</pre></article>`).join('');$('#document-dialog').showModal();}));$$('.delete-document').forEach(b=>b.onclick=guard(async()=>{const doc=documents.find(d=>d.id===b.dataset.id);if(!confirm(`删除「${doc.name}」和它的索引？`))return;await api('/documents/'+doc.id,{method:'DELETE'});toast('文档与索引已删除');await refresh();}));}
$('#file').onchange=guard(async()=>{const file=$('#file').files[0];if(!file)return;const form=new FormData();form.append('file',file);$('#file').disabled=true;toast('正在提取文本并建立索引…');try{const doc=await api('/documents',{method:'POST',body:form});toast(doc.duplicate?'文档已在知识库中':'导入完成，可以提问了');await refresh();}finally{$('#file').disabled=false;$('#file').value='';}});
function render(data){$('#answer').className='answer';$('#answer').textContent=data.answer;$('#answer-mode').textContent={retrieval:'原文检索',ai:'AI 整理','no-evidence':'证据不足'}[data.mode];lastSources=data.sources;$('#sources').innerHTML=data.sources.length?data.sources.map(s=>`<article class="source"><div><span class="source-number">[${s.citation}]</span><strong class="small">${esc(s.name)}</strong></div><p class="small muted">第 ${s.page} 页 · 片段 ${s.idx+1} · 检索分 ${s.score}</p><p>${esc(s.text)}</p></article>`).join(''):empty('暂时没有相关证据','换一个更具体的关键词，或者导入相关资料。');$('#ai-open').classList.toggle('hidden',!data.sources.length);}
$('#question-form').onsubmit=guard(async e=>{e.preventDefault();$('#ask').disabled=true;try{lastQuestion=$('#question').value;render(await post('/ask',{question:lastQuestion,use_ai:false}));}finally{$('#ask').disabled=false;}});
$('#ai-open').onclick=guard(async()=>{const preview=await post('/preview',{question:lastQuestion});$('#preview-content').textContent=JSON.stringify(preview,null,2);$('#preview-dialog').showModal();});$('#preview-close').onclick=()=>$('#preview-dialog').close();$('#document-close').onclick=()=>$('#document-dialog').close();
$('#ai-send').onclick=guard(async()=>{$('#ai-send').disabled=true;try{const data=await post('/ask',{question:lastQuestion,use_ai:true});render(data);$('#preview-dialog').close();}finally{$('#ai-send').disabled=false;}});
$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('#ask-view').classList.toggle('hidden',b.dataset.view!=='ask');$('#documents-view').classList.toggle('hidden',b.dataset.view!=='documents');});
guard(async()=>{config=await api('/config');$('#model').textContent=config.llm.configured?config.llm.model:'离线检索 · API 尚未配置';await refresh();})();
