let selectedBase='',lastMessage=null;
const workspaceControls=document.createElement('div');workspaceControls.className='row';workspaceControls.style.margin='15px 0';workspaceControls.innerHTML='<select id="kb-select" aria-label="知识库"></select><button class="btn secondary" id="new-base">新建知识库</button><button class="btn secondary" id="share-base">访问权限</button><button class="btn secondary" id="reindex">重建索引</button><button class="btn secondary" id="messages-open">问答历史</button><a class="btn secondary" id="kb-backup">备份</a><button class="btn secondary" id="jobs-open">摄取任务</button>';$('#ask-view').prepend(workspaceControls);
const workspaceDialog=document.createElement('dialog');workspaceDialog.innerHTML='<h2 id="workspace-title"></h2><div id="workspace-content"></div><button class="btn secondary" id="workspace-close">关闭</button>';document.body.append(workspaceDialog);$('#workspace-close').onclick=()=>workspaceDialog.close();
function workspaceShow(title,html){$('#workspace-title').textContent=title;$('#workspace-content').innerHTML=html;workspaceDialog.showModal();}
const originalApi=api;api=async(path,options={})=>{if(path==='/documents'&&options.body instanceof FormData)options.body.append('kb_id',selectedBase);if(path==='/documents'&&!(options.body instanceof FormData))path+='?kb_id='+encodeURIComponent(selectedBase);if(['/ask','/preview','/ask-stream'].includes(path)&&typeof options.body==='string'){const body=JSON.parse(options.body);body.kb_id=selectedBase;options={...options,body:JSON.stringify(body)};}return originalApi(path,options);};
// post resolves the current api binding, so scope applies equally to query and generation.
const originalRender=render;render=data=>{originalRender(data);lastMessage=data.message_id;};
async function loadBases(){const bases=await api('/workspace/bases');$('#kb-select').innerHTML=bases.map(k=>`<option value="${k.id}">${esc(k.name)}</option>`).join('');selectedBase=bases[0]?.id||'';$('#kb-backup').href='/api/workspace/bases/'+selectedBase+'/backup';await refresh();}
$('#kb-select').onchange=guard(async()=>{selectedBase=$('#kb-select').value;$('#kb-backup').href='/api/workspace/bases/'+selectedBase+'/backup';lastQuestion='';lastSources=[];$('#answer').textContent='知识库已切换，请重新检索。';$('#sources').innerHTML='';$('#ai-open').classList.add('hidden');await refresh();});
$('#new-base').onclick=guard(async()=>{const name=prompt('知识库名称');if(name){await post('/workspace/bases',{name});await loadBases();}});
$('#share-base').onclick=()=>workspaceShow('知识库访问权限','<form id="share-form"><input id="share-user" placeholder="已注册用户名" required><select id="share-role"><option value="reader">只读</option><option value="editor">可编辑</option></select><button class="btn">授权</button><button class="btn secondary" id="revoke-access" type="button">撤销</button></form><p class="small muted">只有所有者能授权；检索前就过滤知识库权限。</p>');
workspaceDialog.addEventListener('click',e=>{if(e.target.id==='revoke-access')guard(async()=>{await api('/workspace/bases/'+selectedBase+'/members/'+encodeURIComponent($('#share-user').value),{method:'DELETE'});toast('访问权已撤销');workspaceDialog.close();})();});workspaceDialog.addEventListener('submit',e=>{if(e.target.id==='share-form'){e.preventDefault();guard(async()=>{await post('/workspace/bases/'+selectedBase+'/members',{username:$('#share-user').value,role:$('#share-role').value});toast('授权已保存');workspaceDialog.close();})();}});
$('#reindex').onclick=guard(async()=>{const result=await post('/workspace/bases/'+selectedBase+'/reindex',{});toast(`已重建 ${result.chunks} 个片段索引`);});
$('#messages-open').onclick=guard(async()=>{const data=await api('/workspace/messages?kb='+encodeURIComponent(selectedBase));workspaceShow('问答历史',data.map(m=>`<article style="padding:12px 0"><strong>${esc(m.question)}</strong><p class="answer small">${esc(m.answer)}</p><span class="badge">${esc(m.mode)}</span></article>`).join('')||empty('还没有问答记录',''));});
const feedbackButton=document.createElement('button');feedbackButton.className='btn secondary';feedbackButton.textContent='反馈回答';$('#ai-open').after(feedbackButton);feedbackButton.onclick=guard(async()=>{if(!lastMessage)return toast('先完成一次检索或问答');const note=prompt('哪里有帮助，或哪里需要改进？');if(note!==null){await post('/workspace/feedback',{message_id:lastMessage,rating:0,note});toast('反馈已保存');}});
$('#jobs-open').onclick=guard(async()=>{const jobs=await api('/ingest/jobs?kb_id='+encodeURIComponent(selectedBase));workspaceShow('摄取任务',`<label class="btn file-label">后台导入<input type="file" class="hidden" id="async-file" accept=".txt,.md,.pdf"></label>`+jobs.map(j=>`<article style="padding:12px 0"><strong>${esc(j.name)}</strong><p>${esc(j.state)} ${esc(j.error)}</p>${['queued','running'].includes(j.state)?`<button class="btn secondary cancel-job" data-id="${j.id}">取消</button>`:''}${j.state==='failed'?`<button class="btn secondary retry-job" data-id="${j.id}">重试</button>`:''}</article>`).join(''));$('#async-file').onchange=guard(async()=>{const form=new FormData();form.append('file',$('#async-file').files[0]);form.append('kb_id',selectedBase);await api('/ingest/jobs',{method:'POST',body:form});toast('已加入后台任务');workspaceDialog.close();});$$('.cancel-job').forEach(b=>b.onclick=guard(async()=>{await post('/ingest/jobs/'+b.dataset.id+'/cancel',{});workspaceDialog.close();}));$$('.retry-job').forEach(b=>b.onclick=guard(async()=>{await post('/ingest/jobs/'+b.dataset.id+'/retry',{});workspaceDialog.close();}));});
guard(loadBases)();
const semanticButton=document.createElement('button');semanticButton.className='btn secondary';semanticButton.textContent='语义索引';workspaceControls.append(semanticButton);
semanticButton.onclick=guard(async()=>{const preview=await api('/semantic/'+selectedBase+'/preview');workspaceShow('生成语义向量',`<p>模型：${esc(preview.model||'尚未配置')}</p><p>${esc(preview.notice)}，共 ${preview.chunks} 个片段。</p><button class="btn" id="semantic-confirm">确认发送并建立索引</button>`);$('#semantic-confirm').onclick=guard(async()=>{$('#semantic-confirm').disabled=true;try{const result=await post('/semantic/'+selectedBase+'/index',{confirm:true});toast(`已索引 ${result.indexed} 个片段`);workspaceDialog.close();}finally{$('#semantic-confirm').disabled=false;}});});
const semanticLabel=document.createElement('label');semanticLabel.className='small muted';semanticLabel.innerHTML='<input type="checkbox" id="use-semantic"> 查询时使用远程语义向量（发送问题，产生费用）';$('#question-form').append(semanticLabel);
const scopedApi=api;api=async(path,options={})=>{if(['/ask','/preview','/ask-stream'].includes(path)&&typeof options.body==='string'){const body=JSON.parse(options.body);body.semantic=$('#use-semantic').checked;options={...options,body:JSON.stringify(body)};}return scopedApi(path,options);};

const restoreKb=document.createElement('label');restoreKb.className='btn secondary file-label';restoreKb.innerHTML='恢复备份<input type="file" class="hidden" id="restore-kb" accept=".json">';workspaceControls.append(restoreKb);$('#restore-kb').onchange=guard(async()=>{const form=new FormData();form.append('file',$('#restore-kb').files[0]);form.append('kb_id',selectedBase);const result=await api('/workspace/restore-backup',{method:'POST',body:form});toast(`已恢复${result.restored}份文档`);await refresh();});
const baseRefresh=refresh;refresh=async()=>{await baseRefresh();$$('.document-item').forEach(el=>{const id=el.dataset.id;const label=document.createElement('label');label.className='btn secondary file-label';label.innerHTML='更新版本<input type="file" class="hidden" accept=".txt,.md,.pdf">';el.append(label);label.querySelector('input').onchange=guard(async e=>{const form=new FormData();form.append('file',e.target.files[0]);const result=await api('/ingest/documents/'+id+'/revise',{method:'POST',body:form});toast(`更新到版本${result.version}`);await refresh();});});};


const versionRefresh=refresh;refresh=async()=>{await versionRefresh();$$('.document-item').forEach(el=>{const button=document.createElement('button');button.className='btn secondary';button.textContent='版本历史';el.append(button);button.onclick=guard(async()=>{const id=el.dataset.id;const data=await api('/ingest/documents/'+id+'/versions');workspaceShow('文档版本历史',data.map(v=>`<p>版本 ${v.version} · ${esc(new Date(v.created*1000).toLocaleString())} <button class="btn secondary inspect-version" data-version="${v.version}">查看原文</button></p>`).join('')||empty('还没有旧版本','更新文档后保留旧版原文'));$$('.inspect-version').forEach(b=>b.onclick=guard(async()=>{const chunks=await api('/ingest/documents/'+id+'/versions/'+b.dataset.version);$('#workspace-content').innerHTML=chunks.map(c=>`<article><span class="badge">第${c.page}页</span><pre class="answer">${esc(c.text)}</pre></article>`).join('');}));});});};
const auditButton=document.createElement('button');auditButton.className='btn secondary';auditButton.textContent='操作记录';workspaceControls.append(auditButton);auditButton.onclick=guard(async()=>{const data=await api('/workspace/bases/'+selectedBase+'/audit');workspaceShow('知识库操作记录',data.map(r=>`<p>${esc(r.action)} · ${esc(r.detail)} · ${esc(new Date(r.created*1000).toLocaleString())}</p>`).join('')||empty('暂无记录',''));});

